apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "tompa.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tompa.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: {{ .Values.externalSecret.secretStoreKind }}
  target:
    name: {{ include "tompa.secretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: database_url

    - secretKey: JWT_SECRET
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: jwt_secret

    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: google_client_id

    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: google_client_secret

    - secretKey: GITHUB_CLIENT_ID
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: github_client_id

    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.externalSecret.vaultPath }}
        property: github_client_secret
